<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Hse_dashboard_model extends CI_Model
{

    // public $table = 'hse_sasaran_mutu';
    // public $id = 'id';
    // public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

        function get_data_stok(){
        $query = $this->db->query("
SELECT a.departmen, a.audit AS stok, a.goals AS target, b.periode 
FROM hse_sasaran_mutu_detail a
LEFT JOIN hse_sasaran_mutu b ON b.id = a.id_samut
order by b.periode;
 
");
         
        if($query->num_rows() > 0){
            foreach($query->result() as $data){
                $hasil[] = $data;
            }
            return $hasil;
        }
    }

    

}

/* End of file Sasaran_mutu_model.php */
/* Location: ./application/models/Sasaran_mutu_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-06-05 08:33:12 */
/* http://harviacode.com */